[package]
name = "spreadsheet-ods"
version = "0.4.0"
authors = ["thomasscharler <thscharler@gmail.com>"]
edition = "2018"
description = "Read and write ODS files"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/spreadsheet-ods"
keywords = ["ODS", "spreadsheet"]
categories = ["spreadsheet"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ ]
# Dump all XML while reading.
dump_xml = [ ]
# Dump unprocessed XML tags and attributes when reading the ODS.
dump_unused = [ ]
# Apply indentation to the xml output.
indent_xml = []
# Check the xml output for wellformedness.
check_xml = []
# Add bindings for rust_decimal.
use_decimal = []

[dependencies]
rust_decimal = "^1.2.1"
rust_decimal_macros = "^1.2.1"
chrono = "^0.4"
time = "^0.1.42"
zip = "^0.5.4"
quick-xml = "^0.17.2"
color-rs = "^0.5.0"
string_cache = "^0.8.0"
mktemp = "^0.4.0"
