[package]
name = "spreadsheet-ods"
version = "0.9.0"
authors = ["thomasscharler <thscharler@gmail.com>"]
edition = "2018"
description = "Read and write ODS files"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/spreadsheet-ods"
readme = "README.md"
keywords = ["ODS", "spreadsheet"]
categories = ["parser-implementations"]
exclude = [
    ".idea/*",
    ".gitignore",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# Check the xml output for wellformedness.
check_xml = []

[dependencies]
color-rs = "0.6"
string_cache = "0.8"
mktemp = "0.4"
time = "0.1"

[dependencies.quick-xml]
version = "0.22"
# ?? Should be UTF-8, no need for encoding related stuff.
#features = ["encoding"]

[dependencies.zip]
version = "0.5"
default-features = false
features = ["deflate", "time"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "alloc"]