[package]
name = "spreadsheet-ods"
version = "0.2.0"
authors = ["thomasscharler <thscharler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ ]

# Allow for indentation of the output xml
indent_xml = []
# Apply extra checks.
check_xml = []

[dependencies]
rust_decimal = "^1.2.1"
rust_decimal_macros = "^1.2.1"
walkdir = "^2.3.1"
num = "^0.2.1"
log = "^0.4.8"
env_logger = "^0.7.1"
chrono = "^0.4"
time = "^0.1.42"
zip = "^0.5.4"
quick-xml = "^0.17.2"
username = "^0.2.0"
color-rs = "^0.5.0"
string_cache = "0.8.0"