[package]
name = "spreadsheet-ods"
version = "0.12.1"
authors = ["thomasscharler <thscharler@gmail.com>"]
edition = "2021"
description = "Read and write ODS files"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/spreadsheet-ods"
readme = "README.md"
keywords = ["ODS", "spreadsheet", "OpenOffice", "LibreOffice"]
categories = ["parser-implementations"]
exclude = [".idea/*", ".gitignore"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use_decimal", "all_locales"]
# Add conversions from rust_decimal.
use_decimal = []
# Check the xml output for wellformedness.
check_xml = []

all_locales = ["locale_de_AT", "locale_en_US"]
locale_de_AT = []
locale_en_US = []

[dependencies]
rust_decimal = "1.24"
rust_decimal_macros = "1.24"
color-rs = "0.7"
string_cache = "0.8"
mktemp = "0.4"
time = "0.3"
nom = "7.1"
nom_locate = "4.0"
icu_locid = "1.0.0"
lazy_static = "1.4.0"

[dependencies.spreadsheet-ods-cellref]
path = "../spreadsheet-ods-cellref"

[dependencies.quick-xml]
version = "0.26.0"
# ?? Should be UTF-8, no need for encoding related stuff.
#features = ["encoding"]

[dependencies.zip]
version = "0.6"
default-features = false
features = ["deflate", "time"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "alloc"]
